name: we_ship_faas
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  sizer: ^2.0.15
  flutter_svg: ^2.0.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.0.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  another_flushbar: ^1.12.30
  loading_animation_widget: ^1.2.0+4
  logger: ^2.0.2+1
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  file_picker: ^8.1.2
  image_picker: ^1.0.4
  image_cropper: ^8.0.2
  permission_handler: ^11.0.1
  app_settings: ^5.1.1
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.3
  path_provider: ^2.1.1
  http: ^1.1.0
  easy_debounce: ^2.0.3
  rename: ^3.0.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_app_badge: ^2.0.2
  flutter_inappwebview: ^6.1.5
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200

flutter_native_splash:
  color: "#e1f5fe"
  image: assets/images/icon.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/icon.png
    color: "#e1f5fe"
